import { UserProfile } from '../../types';

export const DEMO_USERS: (UserProfile & { defaultPassword: string })[] = [
  {
    id: 'usr-admin-01',
    nik: '1001',
    name: 'Ir. Hendra Wijaya',
    department: 'admin',
    role: 'admin',
    email: 'nik-1001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-rnd-01',
    nik: '2001',
    name: 'Dr. apt. Maya Sari, M.Farm',
    department: 'rnd',
    role: 'manager',
    email: 'nik-2001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-ppic-01',
    nik: '3001',
    name: 'Budi Santoso, S.T.',
    department: 'ppic',
    role: 'supervisor',
    email: 'nik-3001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-qc-01',
    nik: '4001',
    name: 'apt. Rina Anggraeni, S.Farm',
    department: 'quality',
    role: 'manager',
    email: 'nik-4001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-wh-01',
    nik: '5001',
    name: 'Agus Setiawan',
    department: 'warehouse',
    role: 'supervisor',
    email: 'nik-5001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-proc-01',
    nik: '6001',
    name: 'Siti Rahmawati, S.E.',
    department: 'procurement',
    role: 'staff',
    email: 'nik-6001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-sales-01',
    nik: '7001',
    name: 'Deni Kurniawan',
    department: 'sales',
    role: 'staff',
    email: 'nik-7001@pabrik.internal',
    defaultPassword: 'password123',
  },
  {
    id: 'usr-mgmt-01',
    nik: '8001',
    name: 'Bambang Hartono (Director)',
    department: 'management',
    role: 'manager',
    email: 'nik-8001@pabrik.internal',
    defaultPassword: 'password123',
  },
];
